### PR TITLE
Add days-in-past to keep the remote calendar clean.

### PR DESCRIPTION
**Pull request by grauschnabel**
I just started contributing, and checking what is possible with your code.  This is a nice feature I like. :)
The default value switches the feature of, so it should not affect any current configurations for any users.
But some may like that. :)

### CODE REVIEW

**Comment by grauschnabel** [comment]
I'm not sure if this new pull request works, because it is ahead of the old pull request I made.  This now should support vtodo.  Just tell me to change something if it doesn't fit your needs.

For me it works fine, since a week now, I work with that so you can get fixes fast. :)

**Comment by grauschnabel** [comment]
@vanicat, I think tis is solved allready by
`      (let* ((nprio (string-to-number (or (nth 4 tododata) "0")))` in line 1614.
As you see the (or (nth 4 tododata) "0") returns either priority from tododata or "0".  Same as yours.  Maybe yours is faster? I'm not sure about that.

**Comment by vanicat** [comment]
@grauschnabel yes, sorry for the noise, I should have check it

**Comment by dengste** [comment]
I'm sorry it has taken me so long to answer. I'm no longer using org-caldav, but I'll try to get this merged. Your branch is difficult for me to review, because it contains lots of unrelated formatting changes, like changing tabs to whitespace. Please only commit lines you actually need to change. Also, it would help if you could rebase your branch so that later fixes of your commits are already included in the original commits.

**Comment by grauschnabel** [comment]
When I have time I will merge the updates and create a new pull request also with my vtodo changes.  If you don't use it anymore, maybe we could find another maintainer?

**Pull request closed without merging**
